gocardless/gc_ruboconfig

rubocop.yml
* Always use spaces for Layout/SpaceBeforeBlockBraces cop
=> Fixes for Rubocop 0.52

rubocop.yml
This currently raises a false positive on date format strings. Re-enable this once https://github.com/bbatsov/rubocop/pull/5230 is merged.
=> Temporarily disable the Style/FormatStringToken cop

CHANGELOG.md, ruboconfig.gemspec, rubocop.yml
This bumps the Rubocop dependency to the latest version, and reverts a config change we made to deal with a bug in v0.52.0.
=> Bump rubocop to v0.52.1

CHANGELOG.md, README.md, gc_ruboconfig.gemspec
Releasing this on RubyGems will make it easier to version and keep up to date in our dependent projects using Dependabot.
Renaming it from plain old "ruboconfig" to "gc_ruboconfig" will help to make it clear that it conforms to GoCardless's house style, rather than any published style guide.
This PR also bumps the gem a major version to v2.0.0, since it will need to be reconfigured in users' `.ruboconfig.yml` files to point to the new gem name.
=> Rename the gem to gc_ruboconfig, ahead of release on RubyGems

CHANGELOG.md, gc_ruboconfig.gemspec, rubocop.yml
* Setting `DisplayStyleGuide` will include the URL of any appropriate style guide entry, like [this](https://github.com/bbatsov/rubocop/blob/f6d46a281188b2e46af588b7efa215a3688918dc/spec/rubocop/cli_spec.rb#L936) - that's quite nice, as you can go and see why the rule is as such, and sometimes how to fix it/.
* Setting `ExtraDetails` means that cops can include extra helpful details on their offences like [this](https://github.com/bbatsov/rubocop/blob/23876e2e4ed849f2adc976ebe711c4c6a552c8f8/lib/rubocop/cop/message_annotator.rb#L58) - but I can't see any that do that at the moment!
=> More helpful error messages

gc_ruboconfig.gemspec, rubocop.yml
We've been using the [`rubocop-rspec`][] gem with success to standardise on good style in our specs.
Let's start using it in Ruboconfig too, by adding it to the gemspec as a gem dependency, and requiring it in `rubocop.yml` so its cops are available.
Let's also copy over the [`rubocop-rspec`][] related rules from other projects' `.rubocop.yml`s to use them in `gc-ruboconfig`.
We may also want to take some of the rules from `.rubocop_todo.yml`s, but that should be discussed first.
[`rubocop-rspec`]: https://github.com/backus/rubocop-rspec
=> Include rubocop-rspec with Ruboconfig and configure it like existing projects

gc_ruboconfig.gemspec, validate_config.rb
At the moment, `rubocop` and `rubocop-rspec` are defined in the gemspec as development dependencies, so they'll only get installed by Bundler when using the gem in a development capacity.
This isn't working too well for us since adding `rubocop-rspec`, as our shared Rubocop configuration file tries to load that gem and it hasn't been installed, so running Rubocop fails.
This switches to specifying `rubocop` and `rubocop-rspec` (and their versions) as general, rather than development, dependencies.
I think this makes sense, as in reality the configuration is specific to particular versions, since the cops that are available, their behaviour and how they are configurable is all dependent on the current version of these gems.
Specifying the gem versions you have to use here will make sure …
=> Bind to `rubocop` and `rubocop-rspec` as production dependencies

rubocop.yml
The [RSpec/MessageSpies][MessageSpies] cop enforces a particular style for setting message expectations.
`rubocop-rspec`'s default is to use spies. However, as a convention, we've always used mocks and I'm quite happy for it to stay this way. (Although using spies does have some benefits - especially that it only works on test doubles so you can't set expectations all over the place, for example on classes from gems).
This switches to expecting:
```ruby
expect(foo).to receive(:bar)
expect(foo).to have_received(:bar)
```
[MessageSpies]: http://www.rubydoc.info/gems/rubocop-rspec/1.10.0/RuboCop/Cop/RSpec/MessageSpies
=> Configure RSpec/MessageSpies to enforce `expect(foo).to receive(:bar)`

.circleci/config.yml, circle.yml
This switches from CircleCI 1.0 to CircleCI 2.0, slightly adapting the basic [example][] on CircleCI's website.
This makes this project more consistent with other GoCardless codebases, and lets you simply run tests locally with `circleci build` and CircleCI's [CLI][].
[example]: https://circleci.com/docs/2.0/language-ruby/
[CLI]: https://circleci.com/docs/2.0/local-jobs/
=> Run CI using CircleCI 2.0

rubocop.yml
This includes pending tests and any directive prepended with x (xit, xdescribe, xetc…)
=> Enable rspec pending validation

rubocop.yml
This cop implies that `extend self` and `module_function` behave the same way, but they actually handle reflections and private method visibility in slightly different ways. See here for more info:
https://idiosyncratic-ruby.com/8-self-improvement.html
Issue against Rubocop:
https://github.com/rubocop-hq/ruby-style-guide/issues/556
=> Disable Style/ModuleFunction

README.md
As Rails cops have been split out and [deprecated](https://github.com/rubocop-hq/rubocop/pull/7095) from base Rubocop, they must be included separately.
=> Update README with Rails instructions.

gc_ruboconfig.gemspec, rubocop.yml
The new Rubocop release verifies that the Enabled field is a boolean.
=> Bump rubocop to 0.75

CHANGELOG.md, gc_ruboconfig.gemspec, rubocop.yml
We turned this of in one of our main repos and have decided as an organisation that this cop isn't useful for us.
=> Disable RSpec/ImplicitBlockExpectation

CHANGELOG.md, gc_ruboconfig.gemspec
This [library](https://github.com/rubocop-hq/rubocop-performance) adds extra checks for common performance pitfalls, e.g. searching a hash ineffeciently.
We already utilise this in other applications, this just brings it into our libraries by default.
=> Add Rubocop Performance extension

gc_ruboconfig.gemspec, rubocop.yml
This handles the breaking change in https://github.com/rubocop-hq/rubocop/pull/7542.
=> Bump Rubocop to v0.78.0

CHANGELOG.md, gc_ruboconfig.gemspec, rubocop.yml
- [`Layout/SpaceAroundMethodCallOperator`](https://docs.rubocop.org/en/latest/cops_layout/#layoutspacearoundmethodcalloperator)
- [`Style/ExponentialNotation`](https://rubocop.readthedocs.io/en/latest/cops_style/#styleexponentialnotation) (with a 'scientific' notation as default)
Bit unsure about the last one but I suspect we don't use it that much so hopefully it doesn't matter
=> Enable two new cops

CHANGELOG.md, gc_ruboconfig.gemspec, rubocop.yml
These were introduced by 0.81, enabling them by default as they seem sensible.
=> Enable new cops

CHANGELOG.md, gc_ruboconfig.gemspec, rubocop.yml
Namely:
- `Lint/MixedRegexpCaptureTypes`
- `Style/RedundantRegexpCharacterClass`
- `Style/RedundantRegexpEscape`
- `Style/AccessorGrouping`
- `Style/BisectedAttrAccessor`
- `Style/RedundantAssignment`
- `Style/RedundantFetchBlock`
=> Enable support for cops introduced by 0.85

CHANGELOG.md, gc_ruboconfig.gemspec, rubocop.yml
Enables the following cops:
- `Performance/AncestorsInclude`
- `Performance/BigDecimalWithNumericArgument`
- `Performance/RedundantSortBlock`
- `Performance/ReverseFirst`
- `Performance/SortReverse`
- `Performance/Squeeze`
- `Performance/StringInclude`
`Performance/RedundantStringChars` is disabled as it removes some idiomatic code, and does some byte/char moving around encoding which we're not confident with.
=> Enable new cops from rubocop-performance v1.7

CHANGELOG.md, gc_ruboconfig.gemspec, rubocop.yml
- Lint/DuplicateElsifCondition: this prevents some fairly obvious bugs.
- Style/ArrayCoercion: this is good style.  We have a small number of violations, but most are cases where the autocorrect isn't helpful (e.g. replacing `*[*1]` with `Array(1)`, rather than just `[1]`).  Fixing manually feels like the way to go, and is pretty easy.
- Style/CaseLikeIf: nice cleanup with an autocorrect.
- Style/HashAsLastArrayItem: this offers a choice between two different styles, but neither one looks right in all cases.  Have disabled.
- Style/HashLikeCase: no autocorrect, but only a couple of violations that are easy to fix.
- Style/RedundantFileExtensionInRequire: nice style fix with autocorrect
=> Enable new cops for Rubocop v0.88

CHANGELOG.md, gc_ruboconfig.gemspec, rubocop.yml
- Increases the threshold for `Metrics/PerceivedComplexity`: something has changed and now it takes very little for this to be raised.
- Set a larger default for `RSpec/MultipleMemoizedHelpers`: this is a new one, it only takes 5 `let`/`let!` to trigger it... I've raised this to 30 which seems to make sense for most projects.
- Enable/disable a bunch of other cops from rubocop 0.89:
- `Lint/BinaryOperatorWithIdenticalOperands`
- `Lint/DuplicateRescueException`
- `Lint/EmptyConditionalBody`
- `Lint/FloatComparison`
- `Lint/MissingSuper`
- `Lint/OutOfRangeRegexpRef`
- `Lint/SelfAssignment`
- `Lint/TopLevelReturnWithArgument`
- `Lint/UnreachableLoop`
- `Style/ExplicitBlockArgument`
- `Style/GlobalStdStream`
- `Style/SingleArgumentDig`
- `Style/OptionalBooleanParameter` (disabled by default) …
=> Update rubocop and rubocop-rspec cops

CHANGELOG.md, gc_ruboconfig.gemspec, rubocop.yml
- `Lint/DuplicateRequire`
- `Lint/EmptyFile`
- `Lint/TrailingCommaInAttributeDeclaration`
- `Lint/UselessMethodDefinition`
- `Style/CombinableLoops`
- `Style/KeywordParametersOrder`
- `Style/RedundantSelfAssignment`
- `Style/SoleNestedConditional` (disabled by default)
=> Enable support for new cops introduced by rubocop v0.90

CHANGELOG.md, gc_ruboconfig.gemspec, rubocop.yml
Enable support for new cops introduced by rubocop v0.91, v0.92 and v0.93, rubocop-rspec 1.44 and rubocop-performance 1.8:
- `RSpec/StubbedMock` (disabled by default)
- `Performance/Sum`
- `Lint/ConstantDefinitionInBlock`
- `Lint/HashCompareByIdentity`
- `Lint/IdentityComparison`
- `Lint/RedundantSafeNavigation`
- `Lint/UselessTimes`
- `Style/ClassEqualityComparison`
- `Layout/BeginEndAlignment`
Bit on the fence with `Lint/ConstantDefinitionInBlock` as basically makes sense but breaks in rspec (e.g. in `before` blocks). Probably ok with enabling this by default, but then exclude it for anything under `spec`? (have tried this branch on [ps](https://app.circleci.com/pipelines/github/gocardless/payments-service/49081/workflows/ee963f7a-f99e-4d38-97e3-cf17b2635116/jobs/1058195) internally, the …
=> Add support for rubocop 0.93, rubocop-rspec 1.44 and rubocop-performance 1.8

CHANGELOG.md, gc_ruboconfig.gemspec, rubocop.yml
(also disables `Lint/ConstantDefinitionInBlock`)
Need to wait for a proper release of rubocop-rspec before we can merge/release...
=> Support Rubocop 1.0

CHANGELOG.md, gc_ruboconfig.gemspec, rubocop.yml
* Enable support for new cops introduced by rubocop v1.1, v1.2 and v1.3:
- Lint/DuplicateBranch (disabled by default)
- Lint/EmptyBlock (disabled by default)
- Lint/NoReturnInBeginEndBlocks (disabled by default)
- Style/CommentAnnotation (disabled by default)
- Style/DocumentDynamicEvalDefinition (disabled by default)
- Style/NegatedIfElseCondition (disabled by default)
- Lint/DuplicateRegexpCharacterClassElement
- Lint/ToEnumArguments
- Lint/UnmodifiedReduceAccumulator
- Style/ArgumentsForwarding
- Style/CollectionCompact
- Style/NilLambda
- Style/SwapValues
* Enable support for new cops introduced by rubocop-performance 1.9:
- Performance/ArraySemiInfiniteRangeSlice (disabled by default)
- Performance/BlockGivenWithExplicitBlock
- Performance/CollectionLiteralInLoop
- …
=> Support new rubocop-* releases

CHANGELOG.md, gc_ruboconfig.gemspec, rubocop.yml
It is fairly common to define an empty (mock) class in specs, but
shouldn't be a thing in normal app code so disable it only for specs.
=> Disable Lint/EmptyClass for specs

CHANGELOG.md, gc_ruboconfig.gemspec, rubocop.yml
* Add missing Lint/EmptyClass `enabled` flag
* Enabled new cops:
- Style/RedundantArgument
- Lint/UnexpectedBlockArity
Tested this [against ps](https://app.circleci.com/pipelines/github/gocardless/payments-service/53699/workflows/46be55ca-0b91-4ae3-b5b1-c467d1b94568/jobs/1140823) internally, most of the changes are autocorrectable, seems like the major offender is calling `.split(" ")` where the argument can be omitted as [it's a whitespace by default](https://ruby-doc.org/core-2.7.2/String.html#method-i-split).
=> Enable new rubocop 1.6 cops

CHANGELOG.md, gc_ruboconfig.gemspec, rubocop.yml
As above. Tested internally, the only one that needs to be fixed is `Performance/MapCompact` but also can be autocorrected.
=> Enable new cops for rubocop 1.16 and rubocop-performance 1.11

CHANGELOG.md, gc_ruboconfig.gemspec, rubocop.yml
We think the following two cops can encourage changes which
detrimentally affect code readability:
- https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/NegatedIf
- https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/IfUnlessModifier
Thus, we're disabling them.
=> Disable a couple of cops

CHANGELOG.md, gc_ruboconfig.gemspec, rubocop.yml
Enable support for new cops:
- `Layout/LineEndStringConcatenationIndentation`
- `Naming/InclusiveLanguage` (disabled by default)
- `Lint/AmbiguousRange`
- `Style/RedundantSelfAssignmentBranch`
- `RSpec/IdenticalEqualityAssertion`
=> Enable support for new cops

rubocop.yml
Line count lint rules do not result in improvements to code cohesion and often times reduce cohesion by breaking up a meaningful function into several smaller, single-use functions. This change disables the rubocop rule that enforces methods to be a maximum of 10 lines of code.
Discussion: https://gocardless.slack.com/archives/C6ZKC4F4L/p1634648427191900
Places where this rule is disabled or modified to increase line count: https://github.com/search?q=org%3Agocardless+Metrics%2FMethodLength+language%3Ayaml&type=code
=> disable Metrics/MethodLength lint rule

rubocop.yml
Disabling this cop as it makes it unclear what is actually creating test resources.
Conversation on slack: https://gocardless.slack.com/archives/C6ZKC4F4L/p1641398837205400
=> Disable RSpec/FactoryBot/SyntaxMethods

CHANGELOG.md, gc_ruboconfig.gemspec
Release of https://github.com/gocardless/gc_ruboconfig/pull/89
=> Prepare for v2.30.0 release

CHANGELOG.md, gc_ruboconfig.gemspec, rubocop.yml
The default values are incredibly low and force to write a lot of one liners.
(We already have these settings almost everywhere)
=> Set sensible defaults for 'complexity' metrics

CHANGELOG.md, gc_ruboconfig.gemspec, rubocop.yml
Adding support for new cops:
* Enabled cops:
- `Performance/StringIdentifierArgument` - Only pass symbols to `send`
- `Style/MapToHash` - Prefer `to_h {}` over `map {}.to_h`
- `Style/NumberedParameters` - Only allow numbered params on single lines
- `Style/NumberedParametersLimit` - Cap number of numbered params at 2
- `Security/IoMethods` - Disallow direct access to `IO.read` methods
- `Gemspec/RequireMFA` - Require MFA annotation on gemspecs
- `Lint/AmbiguousOperatorPrecedence` - Wrap arguments in parenthesis to denote operator preference
- `Lint/IncompatibleIoSelectWithFiberScheduler` -
- `Lint/RequireRelativeSelfPath` - Don't `require_relative` on self
- `Lint/UselessRuby2Keywords`
- `Naming/BlockForwarding` - Prefer `def foo(&block)` over `def foo(&)`
- …
=> Add support for new cops

CHANGELOG.md, README.md, gc_ruboconfig.gemspec, rubocop.yml
We currently import these definitions separately for each rails project, leading to inconsistent cop usage per service﻿
=> Include rubocop-rails

CHANGELOG.md, gc_ruboconfig.gemspec, rubocop.yml
The `Gemspec/DateAssignment` cop has been removed from rubocop and the suggested
replacemnt is `Gemspec/DeprecatedAttributeAssignment` cop.
=> Replaces removed cop with suggested alternative

gc_ruboconfig.gemspec
Currently a CI step on all new our service PRs is failing as the latest version of rubocop-rspec is missing the obselete.yml file..
While the fix is not released we should fall-back to the working version, v2.12.1
=> Fix the rubocop-rspec to v2.12.1 until the v2.3.0 is fixed

CHANGELOG.md, gc_ruboconfig.gemspec
Update rubocop-rspec requirement to be >=2.13.1
The [release](https://github.com/rubocop/rubocop-rspec/releases/tag/v2.13.1) fixed the issue in v2.13.0, so okay to bump to latest version
=> Update rubocop-rspec requirement to be >=2.13.1

CHANGELOG.md, gc_ruboconfig.gemspec, rails.yml, rubocop.yml
Rather than having to remember the symbols for each http status we can
just use the numeric values as usual
=> Setting RSpec/Rails/HttpStatus style to numeric

CHANGELOG.md, gc_ruboconfig.gemspec, rails.yml, rubocop.yml
```yaml
RSpec/Rails/InferredSpecType: # new in 2.14
Enabled: false
Rails/ActionOrder: # new in 2.17
Enabled: false
Rails/IgnoredColumnsAssignment: # new in 2.17
Enabled: true
Rails/WhereNotWithMultipleConditions: # new in 2.17
Enabled: false
Lint/DuplicateMagicComment: # new in 1.37
Enabled: true
Style/OperatorMethodCall: # new in 1.37
Enabled: true
Style/RedundantStringEscape: # new in 1.37
Enabled: true
RSpec/SortMetadata: # new in 2.14
Enabled: true
RSpec/Capybara/NegationMatcher: # new in 2.14
Enabled: true
RSpec/Capybara/SpecificActions: # new in 2.14
Enabled: false
RSpec/FactoryBot/ConsistentParenthesesStyle: # new in 2.14
Enabled: false
```
=> Add new cops v3.6.0

CHANGELOG.md, gc_ruboconfig.gemspec, rubocop.yml
This addresses the following errors when running rubocop in payments-service:
```
~gems/gc_ruboconfig-3.6.0/rubocop.yml: RSpec/Capybara/SpecificFinders has the wrong namespace - should be Capybara
~gems/gc_ruboconfig-3.6.0/rubocop.yml: RSpec/Capybara/SpecificMatcher has the wrong namespace - should be Capybara
~gems/gc_ruboconfig-3.6.0/rubocop.yml: RSpec/Capybara/NegationMatcher has the wrong namespace - should be Capybara
~gems/gc_ruboconfig-3.6.0/rubocop.yml: RSpec/Capybara/SpecificActions has the wrong namespace - should be Capybara
```
=> Fix warnings on the `RSpec/Capybara` namespace

.github/workflows/release.yml, CHANGELOG.md, gc_ruboconfig.gemspec
This adds a GitHub workflow to automate the release process of the gem when we're cutting a new release (precisely, when we create a tag -- we don't necessarily need to create a full-fledged GitHub release).
=> Automate publish process

.github/workflows/tests.yml, CHANGELOG.md, gc_ruboconfig.gemspec
We haven't supported Ruby 2.6 for a while now at GC so there's no reason to keep supporting it in this gem, and it's preventing dependency updates
We don't support Ruby 2.7 either, but current RSpec still does, so I've left it in for now
=> Drop support for Ruby 2.6

CHANGELOG.md, gc_ruboconfig.gemspec, rubocop.yml
This fixes the following errors when running rubocop >= 2.22.0 as FactoryBot cops have been moved into the `rubocop-factory_bot` gem
```
.rubocop.yml: RSpec/FactoryBot/SyntaxMethods has the wrong namespace - should be FactoryBot
.rubocop.yml: RSpec/FactoryBot/ConsistentParenthesesStyle has the wrong namespace - should be FactoryBot
```
=> Fix warnings on the `RSpec/FactoryBot` namespace

gc_ruboconfig.gemspec, rubocop.yml
We've found that 90 chars is quite limiting and workarounds tend to be less readable. So increase limit to 100
=> Increase linelength limit to 120

CHANGELOG.md, gc_ruboconfig.gemspec, rubocop.yml
We felt that this was too ambiguous and that it may confuse people who
are new to Ruby as to what the operator means/meant to do.
=> Set UseAnonymousForwarding to false

rubocop.yml
Some of our legacy code relies on returning nil from predicate methods to indicate things such as missing values, so this would be changing behaviour
https://docs.rubocop.org/rubocop/cops_style.html#stylereturnnilinpredicatemethoddefinition
=> Disable Style/ReturnNilInPredicateMethodDefinition

CHANGELOG.md, gc_ruboconfig.gemspec, rubocop.yml
```
[1] (main)> [["AA", "a"]].each { |key, value| puts key.to_s }
AA
=> [["AA", "a"]]
[2] (main)> [["AA", "a"]].each_key { |key, value| puts key.to_s }
NoMethodError: undefined method `each_key' for [["AA", "a"]]:Array
from (pry):2:in `__pry__'
[3] (main)> [["AA", "a"]].to_h.each_key { |key, value| puts key.to_s }
AA
=> {"AA"=>"a"}
```
=> Disable rule as it's misbehaving

gc_ruboconfig.gemspec, rails.yml
```
Error: Ambiguous cop name `RSpec/Rails/HttpStatus` used in
/Users/krobayna/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/gc_ruboconfig-4.4.1/rails.yml
needs department qualifier. Did you mean Rails/HttpStatus or
RSpecRails/HttpStatus?
```
The rule was updated
https://docs.rubocop.org/rubocop-rspec_rails/cops_rspecrails.html#rspecrailshttpstatus
=> Ensure rubocop can parse rules

rubocop.yml
Autocorrecting this can lead to confusing results, an example of this going wrong is at # https://github.com/gocardless/abacus/pull/3268#pullrequestreview-1809073293
So we decided to disable it instead since it is quite low value to have.
=> Disable RSpec/ExampleWording

CHANGELOG.md, capybara.yml, gc_ruboconfig.gemspec, rails.yml, rubocop.yml
Came across error in different gem when rubocop-rspec version was auto bumped to 3.0.1. 
So seems from 3.0.0 >= the cops are separated in different repos, so they need to added as separate gems and you need require in yml file. 
Described changes: https://docs.rubocop.org/rubocop-rspec/upgrade_to_version_3.html
=> Update for rubocop-rspec 3.0.0 >=

capybara.yml, gc_ruboconfig.gemspec, rubocop.yml
These ones should be prefixed by RSpec as otherwise we get an error
=> Change how rules are referenced

gc_ruboconfig.gemspec
Followup to #127
Update the minimum required versions of dependencies to the versions in which they were converted to be plugins, so that the updated config to use them as plugins doesn't break downstream consumers with differing version constraints
See:
* https://github.com/rubocop/rubocop-rspec/releases/tag/v3.5.0
* https://github.com/rubocop/rubocop-rails/releases/tag/v2.30.0
* https://github.com/rubocop/rubocop-performance/releases/tag/v1.24.0
=> Update minimum required versions of pluginified dependencies
